# MQTT Source for Edge Services
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: mqtt-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: mqtt-source
    properties:
      brokerUrl: "tcp://mosquitto:1883"
      topic: "mytopic"
  sink:
    ref:
      kind: Service
      apiVersion: serving.knative.dev/v1
      name: edge-service